services:
  kong:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,simple-go-plugin
      KONG_PLUGINSERVER_NAMES: simple-go-plugin
      KONG_PLUGINSERVER_SIMPLE_GO_PLUGIN_SOCKET: /tmp/simple-go-plugin.socket
      KONG_PLUGINSERVER_SIMPLE_GO_PLUGIN_START_CMD: /usr/local/bin/simple-go-plugin
      KONG_PLUGINSERVER_SIMPLE_GO_PLUGIN_QUERY_CMD: /usr/local/bin/simple-go-plugin -dump
    volumes:
      - ./kong.yml:/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - kong-net

  httpbin:
    image: kennethreitz/httpbin:latest
    container_name: test-httpbin
    ports:
      - "8080:80"
    networks:
      - kong-net

networks:
  kong-net:
