version: '3.8'

services:
  lua-embedding-demo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./go-lua-host:/app/go-lua-host
      - ./lua-scripts:/app/lua-scripts
      - ./examples:/app/examples
    working_dir: /app
    command: ["./lua-embedding-demo", "basic"]
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    networks:
      - lua-demo

  # Serviço interativo para testar diferentes exemplos
  lua-interactive:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./go-lua-host:/app/go-lua-host
      - ./lua-scripts:/app/lua-scripts
      - ./examples:/app/examples
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]  # Manter container rodando
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    networks:
      - lua-demo

networks:
  lua-demo:
    driver: bridge
